# Generated by Django 5.1.2 on 2024-10-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_storage_product_storage_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storage_variant',
        ),
        migrations.AddField(
            model_name='storage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_variants', to='products.product'),
            preserve_default=False,
        ),
    ]
